In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
arr = np.full(10, 2.5)
arr

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
arr = np.array([1,3,5,7,9,12])
arr

array([ 1,  3,  5,  7,  9, 12])

In [7]:
arr[2]

np.int64(5)

In [8]:
arr[2] = 15

In [9]:
arr

array([ 1,  3, 15,  7,  9, 12])

In [10]:
arr = np.arange(3, 10)
arr

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
arr = np.linspace(0, 100, 11)
arr

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [14]:
# Two Dimentional arrays

In [16]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr[(0,1)]

np.int64(2)

In [20]:
arr[0,1]

np.int64(2)

In [22]:
arr[2]

array([7, 8, 9])

In [23]:
arr[:,2]

array([3, 6, 9])

In [24]:
arr[2] = [1,1,1]

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [26]:
arr[:,2] = [1,2,3]

In [27]:
arr

array([[1, 2, 1],
       [4, 5, 2],
       [1, 1, 3]])

In [45]:
np.random.seed(2)
arr = 100 * np.random.rand(5,2)

In [46]:
arr

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [49]:
np.random.seed(2)
arr = np.random.randn(5,2)
arr

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [53]:
np.random.seed(2)
arr = np.random.randint(low=0, high=100, size=(5,2))
arr

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [55]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [56]:
arr = 1 + arr
arr

array([1, 2, 3, 4, 5])

In [57]:
arr = 2 * arr
arr

array([ 2,  4,  6,  8, 10])

In [59]:
arr = np.arange(5)
b = (10 + (arr * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [60]:
arr + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [61]:
arr >= 2

array([False, False,  True,  True,  True])

In [62]:
arr > b

array([False, False,  True,  True,  True])

In [64]:
arr[arr>b]

array([2, 3, 4])

In [65]:
arr.min()

np.int64(0)

In [66]:
arr.sum()

np.int64(10)

In [67]:
arr.mean()

np.float64(2.0)

In [68]:
arr.std()

np.float64(1.4142135623730951)

In [71]:
u = np.array([2,4,5,6])

In [72]:
u

array([2, 4, 5, 6])

In [73]:
v = np.array([1,0,0,2])

In [74]:
v

array([1, 0, 0, 2])

In [75]:
u.shape[0]

4

In [76]:
v.shape[0]

4

In [77]:
arr = u * v

In [78]:
arr.sum()

np.int64(14)

In [79]:
print(arr.sum())

14


In [80]:
u.dot(v)

np.int64(14)

In [81]:
v.dot(u)

np.int64(14)