In [1]:
import numpy as np

In [2]:
# multiply a vector by a scalar value

In [3]:
u = np.array([2,4,5,6])
u * 2

array([ 4,  8, 10, 12])

Vector-Vector Multuplication

In [4]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [5]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0], "size not same"
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    #print(result)
    return result
        

In [6]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [7]:
u.shape

(4,)

In [8]:
arr = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,9]])

In [9]:
arr.shape

(3, 4)

In [10]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 9]])

In [11]:
U = np.array([[2,4,5,6], [1,2,1,2],[3,1,2,1]])

In [12]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [13]:
v = np.array([1,0.5,2,1])

In [14]:
v

array([1. , 0.5, 2. , 1. ])

In [15]:
def matrix_vector_multiplication(u,v):
    assert u.shape[1] == v.shape[0], "matrix row size and vector size not matching"
    n = u.shape[0]
    result = np.zeros(n)
    #print(result)
    for i in range(n):
        #print(u[i,:])
        #print(v)
        result[i] = vector_vector_multiplication(u[i], v)
    print(result)

In [16]:
U[0]

array([2, 4, 5, 6])

In [17]:
matrix_vector_multiplication(U,v)

[20.   6.   8.5]


In [18]:
U.dot(v)

array([20. ,  6. ,  8.5])

Matrix - Matrix Multiplication

In [19]:
V = np.array([[1, 1, 2], [0, 0.5, 1], [0, 2, 1], [2, 1, 0],])

In [20]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [21]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])