In [1]:
import numpy as np

In [2]:
xi = [453, 11, 86]

In [3]:
w0 = 7.17

In [4]:
w = [0.01, 0.04,0.002]

In [5]:
xi = [1] + xi

In [6]:
wi = [w0] + w

In [7]:
xi

[1, 453, 11, 86]

In [8]:
wi

[7.17, 0.01, 0.04, 0.002]

In [10]:
xi = np.array(xi)

In [11]:
xi

array([  1, 453,  11,  86])

In [12]:
xiT = xi.T

In [13]:
xiT

array([  1, 453,  11,  86])

In [14]:
wi = np.array(wi)

In [15]:
wi

array([7.17e+00, 1.00e-02, 4.00e-02, 2.00e-03])

In [16]:
xiT@wi

np.float64(12.312)

In [17]:
xi@wi

np.float64(12.312)

In [18]:
wi@xi

np.float64(12.312)

In [19]:
x1  = [1, 148, 24, 1385]
x2  = [1, 132, 25, 2031]
x10 = [1, 453, 11, 86]

X = [x1, x2, x10]
X = np.array(X)

In [20]:
X

array([[   1,  148,   24, 1385],
       [   1,  132,   25, 2031],
       [   1,  453,   11,   86]])

In [21]:
X@wi

array([12.38 , 13.552, 12.312])

In [22]:
XT = X.T

In [23]:
XT

array([[   1,    1,    1],
       [ 148,  132,  453],
       [  24,   25,   11],
       [1385, 2031,   86]])

In [25]:
X = [
    [148, 24, 1385],
    [132, 25, 2031],
    [453, 11, 86],
    [158, 24, 185],
    [172, 25, 201],
    [413, 11, 86],
    [38,  54, 185],
    [142, 25, 431],
    [453, 31, 86],
]
X = np.array(X)

In [41]:
X
def dot(xi, w):
    n = len(xi)

    res = 0.0

    for j in range(n):
        res = res + xi[j] * w[j]

    return res

In [42]:
XT = X.T

In [43]:
XT

array([[ 148,  132,  453,  158,  172,  413,   38,  142,  453],
       [  24,   25,   11,   24,   25,   11,   54,   25,   31],
       [1385, 2031,   86,  185,  201,   86,  185,  431,   86]])

In [50]:
XTX = XT@X

In [51]:
XTX

array([[ 696471,   44115,  718540],
       [  44115,    7146,  118803],
       [ 718540,  118803, 6359986]])

In [52]:
XTXi = np.linalg.inv(XTX)

In [53]:
XTXi

array([[ 2.35803616e-06, -1.46900642e-05,  8.00007928e-09],
       [-1.46900642e-05,  2.94487947e-04, -3.84130606e-06],
       [ 8.00007928e-09, -3.84130606e-06,  2.28083884e-07]])

In [60]:
(XTX@(XTXi)).round(1)

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])