In [2]:
import numpy as np

In [19]:
X = [
    [148, 24, 1385],
    [132, 25, 2031],
    [453, 11, 86],
    [158, 24, 185],
    [172, 25, 201],
    [413, 11, 86],
    [38,  54, 185],
    [142, 25, 431],
    [453, 31, 86],
]
X = np.array(X)

In [20]:
y = [100, 200, 150, 250, 100, 200, 150, 250, 120]

In [7]:
ones = np.ones(X.shape[0])

In [8]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
X = np.column_stack([ones,X])

In [11]:
X

array([[1.000e+00, 1.480e+02, 2.400e+01, 1.385e+03],
       [1.000e+00, 1.320e+02, 2.500e+01, 2.031e+03],
       [1.000e+00, 4.530e+02, 1.100e+01, 8.600e+01],
       [1.000e+00, 1.580e+02, 2.400e+01, 1.850e+02],
       [1.000e+00, 1.720e+02, 2.500e+01, 2.010e+02],
       [1.000e+00, 4.130e+02, 1.100e+01, 8.600e+01],
       [1.000e+00, 3.800e+01, 5.400e+01, 1.850e+02],
       [1.000e+00, 1.420e+02, 2.500e+01, 4.310e+02],
       [1.000e+00, 4.530e+02, 3.100e+01, 8.600e+01]])

In [12]:
XT = X.T

In [13]:
XTX = XT@X

In [15]:
XTXi = np.linalg.inv(XTX)

In [25]:
XTXi@XT@y

array([ 3.00067767e+02, -2.27742529e-01, -2.57694130e+00, -2.30120640e-02])

In [21]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [22]:
w0,w = train_linear_regression(X,y)

In [23]:
w0

np.float64(300.0677669255554)

In [24]:
w

array([-0.22774253, -2.5769413 , -0.02301206])

In [26]:
l = [1,2,3,4,5]

In [28]:
for i,j in enumerate(l):
    print(i,j)

0 1
1 2
2 3
3 4
4 5


In [29]:
l = ['a','b','c','d','e']

In [30]:
for i,j in enumerate(l):
    print(i,j)

0 a
1 b
2 c
3 d
4 e


In [31]:
d = {'name':'Karthi','age':41}

In [32]:
for i,j in enumerate(d):
    print(i,j)

0 name
1 age
